### ISSUE TITLE
Resource fails when setting owner

### ISSUE THREAD

**Issue by wolf31o2** [chef-cookbooks/ark#181]
### Cookbook version
2.2.0

### Chef-client version
12.4.3

### Platform Details
Happens reliably in automated testing on every platform I've tested.

### Scenario:
Use `ark` resource w/ `owner` attribute.

### Steps to Reproduce:
Use `ark` resource w/ `owner` attribute set.

### Expected Result:
Extract my ZIP file.

### Actual Result:
```
    cdap-sdk-ami: ================================================================================
    cdap-sdk-ami: Error executing action `install` on resource 'ark[sdk]'
    cdap-sdk-ami: ================================================================================
    cdap-sdk-ami:
    cdap-sdk-ami: NoMethodError
    cdap-sdk-ami: -------------
    cdap-sdk-ami: undefined method `owner=' for LWRP resource ark from cookbook ark
```
